Ismael.herrera/modulo 2
ismaelherrera1/TheMovieDB pull request #1
Opened 2023-08-22 12:42 UTC by ismaelherrera1

-Possible ui
-Movie card class implemented
-Like counter functionality was added
![Screenshot_20230818_125632](https://github.com/ismaelherrera1/TheMovieDB/assets/142032513/90776397-4f95-48ec-be67-bdc6c6c3f04e)

2023-08-22 13:31 UTC, LeonardoMolleker commented on lib/main.dart
> +            top: true, bottom: true, left: true, right: true,
Unnecesary parameters, top, bottom, left, right are true by default

2023-08-22 13:31 UTC, LeonardoMolleker commented on lib/main.dart
> +          title: Text('Movies App',),
constant

2023-08-22 13:32 UTC, LeonardoMolleker commented on lib/movie_card.dart
> +    double rating = 7.8;
Make all these variables constants

2023-08-22 13:32 UTC, LeonardoMolleker commented on lib/movie_card.dart
> +                    image: NetworkImage('https://westvanlibrary.ca/wp-content/uploads/2023/06/02-smb-dm-mobile-banner-1080x745-pl-f01-022723-63fe3cbc4df54-1.jpg',),
constant

2023-08-22 13:32 UTC, LeonardoMolleker commented on lib/movie_card.dart
> +                    'The Super Mario Bros. Movie',
constant

2023-08-22 14:08 UTC, MarcosCGlobant requested changes

2023-08-22 14:08 UTC, MarcosCGlobant commented on lib/main.dart
> +            borderRadius: BorderRadius.only(bottomLeft: Radius.circular(25), bottomRight: Radius.circular(25),),
format the code to fix this indentation

2023-08-22 14:08 UTC, MarcosCGlobant commented on lib/movie_card.dart
> +                    ElevatedButton(onPressed: (){}, child: Icon(Icons.play_circle,),),
format the code to fix the indentation

2023-08-22 14:08 UTC, MarcosCGlobant commented on lib/movie_card.dart
> +                    decoration: const ShapeDecoration(color: Colors.redAccent, shape: StarBorder(points: 5,),),
add the value into a constant

2023-08-22 14:08 UTC, MarcosCGlobant commented on lib/movie_card.dart
> +              padding: EdgeInsets.all(8.0,),
add the value into a constant

2023-08-22 14:08 UTC, MarcosCGlobant commented on lib/movie_card.dart
> +                        Text('$counter users liked this movie.', style: TextStyle(fontWeight: FontWeight.bold,),),
add the hardcoded values into a constants

2023-08-22 14:08 UTC, MarcosCGlobant commented on lib/movie_card.dart
> +                    height: 250,
add the hardcoded values into a constants

2023-08-22 16:04 UTC, LeonardoMolleker commented on lib/main.dart
> +          )),
trailing comma

2023-08-22 16:05 UTC, LeonardoMolleker commented on lib/main.dart
> +          )),
comma

2023-08-22 16:05 UTC, LeonardoMolleker commented on lib/main.dart
> +        ));
comma

2023-08-22 16:18 UTC, LeonardoMolleker commented on lib/movie_card.dart
> +  double posterHeight = 250;
you could use const keyword here

2023-08-22 19:50 UTC, matiasilveiro-gl requested changes

2023-08-22 19:50 UTC, matiasilveiro-gl commented on lib/movie_card.dart
> +  );
It'd be better to have this as an array of genres, and then concatenate it into a single string (like you have here), as it's closer to the actual payload of the API we'll work with

2023-08-22 19:50 UTC, matiasilveiro-gl commented on lib/movie_card.dart
> +  @override
Line break here

2023-08-22 19:50 UTC, matiasilveiro-gl commented on lib/movie_card.dart
> +            Row(
This `Row` is not needed, as it has a single child.

2023-08-22 19:50 UTC, matiasilveiro-gl commented on lib/movie_card.dart
It'd be better to split your widget tree in sections of smaller and standalone widgets. By extracting widgets you can end up having a root structure like:
```
Column(
    children: [
      MovieHeader(...),
      MovieActions(...),
      MovieGenres(...),
      MovieOverview(...)
   ],
)
```
Much more readable than a huge widget tree, and much more sustainable too!

2023-08-24 13:36 UTC, ismaelherrera1 commented
![Screenshot_20230824_103448](https://github.com/ismaelherrera1/TheMovieDB/assets/142032513/584af66c-883f-462e-aaec-9bd3606d8ef4)

2023-08-24 13:59 UTC, LeonardoMolleker commented on lib/main.dart
> +                25,
constants here

2023-08-24 15:37 UTC, matiasilveiro-gl reviewed
As of now, your app is only prepared to show the Mario Bros movie details. If you wanted to show another movie, you'd have to traverse through all your widgets and update a bunch of constants.
My proposal is to do a refactor, create a `Movie` data class to hold all the details of your movie, and make all. the widgets depend on that instance as well, instead of spread constants.
Thoughts?

2023-08-24 15:37 UTC, matiasilveiro-gl commented on lib/movie_overview.dart
As most of the constants are related to a specific movie (and this app will grow to show the details of different movies) I'd do this:

- Create a Movie class (useful for Modules 3 and up).
- Create a mocked movie instance for the Super Mario movie.
- Make all widgets depend on the Movie class parameters, instead of the constants.

2023-08-24 15:37 UTC, matiasilveiro-gl commented on lib/main.dart
> +      home: Scaffold(
I'd move the entire `Scaffold` to a separate `MovieDetailsPage` widget or something like that, leaving things a little bit prepared for module 3.

2023-08-24 15:37 UTC, matiasilveiro-gl commented on lib/movie_actions.dart
> +    double fontSize = screenWidth / 15;
Bad idea! Font sizing is managed by the TextStyle inside the Material theme. It also has auto-scaling based on your device's font scaling as well.

2023-08-24 21:37 UTC, MarcosCGlobant approved these changes

2023-08-28 14:50 UTC, LeonardoMolleker approved these changes

2023-08-28 15:14 UTC, matiasilveiro-gl requested changes

2023-08-28 15:14 UTC, matiasilveiro-gl commented on lib/movie.dart
This shouldn't extend StatelessWidget, as it's intended to just hold data, not a widget! It should be a pure Dart class

2023-08-28 15:14 UTC, matiasilveiro-gl commented on lib/movie_header.dart
> +  );
Remove this

2023-08-28 15:14 UTC, matiasilveiro-gl commented on lib/movie_header.dart
> +            image: backdrop,
This should come from the `backdropPath` parameter, right? 
Also, useful tip: see `Image.network` constructor!

2023-08-28 15:14 UTC, matiasilveiro-gl commented on lib/movie_overview.dart
> +  );
Remove this

2023-08-28 15:14 UTC, matiasilveiro-gl commented on lib/movie_overview.dart
> +  ];
You should get these from the parameters!

2023-08-28 15:17 UTC, ismaelherrera1 commented on lib/movie.dart
Didnt notice until now, makes sense. I've just changed it to pure dart class 👍

2023-08-28 15:27 UTC, Kevin-Guillen requested changes
We could start from now organizing the project in different folders for the widgets , utils(ui_constants) and screens.

2023-08-29 13:52 UTC, Kevin-Guillen commented on lib/screens/movie_card.dart
>  class MovieCard extends StatefulWidget {
We could rename this to something like MovieDetails , its a more representative name for a screen. MovieCard sound more like an specific widget.

2023-08-29 18:37 UTC, matiasilveiro-gl commented on lib/screens/movie_card.dart
> +  final sampleMovie = const Movie(
This movie could be passed as parameter instead of creating that here

2023-08-29 18:37 UTC, matiasilveiro-gl commented on lib/screens/movie_card.dart
> +        leading: Builder(
Why this `Builder` widget here?

2023-08-29 18:37 UTC, matiasilveiro-gl commented on lib/screens/movie_card.dart
> +            MovieActions(sampleMovie.voteAverage, sampleMovie.voteCount,),
Autoformat

2023-08-29 18:37 UTC, matiasilveiro-gl commented on lib/widgets/movie_overview.dart
> +            image: poster,
This should be an `Image.network(...)` with the poster URL (related to the `posterPath` parameter)

2023-08-29 18:37 UTC, matiasilveiro-gl commented on mocks/genres.json
Remove this file, that's for the following PR

2023-08-29 18:37 UTC, matiasilveiro-gl commented on mocks/movies.json
Remove this file, that's for the following PR

2023-08-31 11:31 UTC, FranciscoGaraventa commented on lib/main.dart
> +    );
You can move this mock movie object as a factory method to the Movie class, to avoid to create on UI side

2023-08-31 11:32 UTC, FranciscoGaraventa commented on lib/main.dart
> +    );
And also you forgot to add a trailing comma after "Commedy"

2023-08-31 11:34 UTC, FranciscoGaraventa commented on lib/widgets/movie_overview.dart
> +            image: NetworkImage('https://image.tmdb.org/t/p/w500/$posterPath'),
Nice inclusion of the image call, as a suggestion i recommend to move the creation of the link on the movie side, so voy are going to have a method like
`String get fullPosterPath => 'https://image.tmdb.org/t/p/w500/$posterPath'`
that return the complete url and on the UI side you only need to do this:
`NetworkImage(movie.fullPosterPath)`

2023-08-31 13:47 UTC, matiasilveiro-gl approved these changes
LGTM! With minor comments

2023-08-31 13:47 UTC, matiasilveiro-gl commented on lib/widgets/movie.dart
> +}
EOF

2023-08-31 13:47 UTC, matiasilveiro-gl commented on lib/main.dart
> +import 'package:the_movie_db/widgets/movie.dart';
Relative imports

2023-08-31 13:47 UTC, matiasilveiro-gl commented on lib/screens/movie_details.dart
> +class MovieDetails extends StatefulWidget {
I don't see any inner state, so it could be a `StatelessWidget` instead

2023-08-31 13:47 UTC, matiasilveiro-gl commented on lib/screens/movie_details.dart
> +import 'package:the_movie_db/utils/ui_constants.dart';
Relative imports

2023-09-01 12:30 UTC, Kevin-Guillen approved these changes

2023-09-01 13:47 UTC, FranciscoGaraventa approved these changes
LG

2023-09-01 13:48 UTC, merged