bloc, drawer and tests implemented
ismaelherrera1/TheMovieDB pull request #4
Opened 2023-10-23 13:14 UTC by ismaelherrera1

Important aspects implemented to the project:
- BloC pattern
- Drawer
- Grid View
- Page View
- Widget & Unit testing
https://github.com/ismaelherrera1/TheMovieDB/assets/142032513/3e414902-e275-4b60-bf70-4e4785451ab6

2023-10-23 13:58 UTC, FranciscoGaraventa commented on lib/src/core/util/data_state.dart
> +  DataState({required this.state, this.data, this.error});
trailing comma

2023-10-23 13:58 UTC, FranciscoGaraventa commented on lib/src/core/util/data_state.dart
> +  SuccessState(T data) : super(state: BaseState.success, data: data);
Same as above

2023-10-23 13:58 UTC, FranciscoGaraventa commented on lib/src/core/util/data_state.dart
> +  FailState(String error): super(state: BaseState.failure, error: error);
Same as above

2023-10-23 13:58 UTC, FranciscoGaraventa commented on lib/src/core/util/enum_categories.dart
> +  now_playing
Format and also trailing comma

2023-10-23 13:59 UTC, FranciscoGaraventa commented on lib/src/core/util/enum_states.dart
> +enum BaseState{
Same as above

2023-10-23 13:59 UTC, FranciscoGaraventa commented on lib/src/core/util/mappers/mapper.dart
> +    return Genre(id: genreModel.id, name: genreModel.name);
trailing comma

2023-10-23 14:01 UTC, FranciscoGaraventa commented on lib/src/data/datasource/remote/movie_api_provider.dart
> +    if (response.statusCode == 200) {
Here you can use instead to 200, HttpStatus.OK

2023-10-23 14:01 UTC, FranciscoGaraventa commented on lib/src/data/datasource/remote/movie_api_provider.dart
> +    if (response.statusCode == 200) {
Same as above

2023-10-23 14:02 UTC, FranciscoGaraventa commented on lib/src/data/model/genre_model.dart
> +class GenreDataModel {
trailling commas and also you dont' need to define as late the parameters

2023-10-23 14:07 UTC, FranciscoGaraventa commented on lib/src/data/model/movie_list_model.dart
> +    }
You can change this kind of code with:
`List<MovieDataModel>.from(json['results']).map((movie) => MovieDataModel.fromJson(movie)).toList();`

2023-10-23 14:08 UTC, FranciscoGaraventa commented on lib/src/data/model/movie_model.dart
> +      //required super.originalTitle,
why this is commented?

2023-10-23 14:08 UTC, FranciscoGaraventa commented on lib/src/data/model/movie_model.dart
> +        //originalTitle: json['original_title'],
Same as above

2023-10-23 14:09 UTC, FranciscoGaraventa commented on lib/src/data/model/movie_model.dart
> +  int get getVoteCount => voteCount;
This getters are not necessary

2023-10-23 14:10 UTC, FranciscoGaraventa commented on lib/src/data/model/now_playing_movies_model.dart
> +    }
Same suggestion as i mentioned above

2023-10-23 14:11 UTC, FranciscoGaraventa commented on lib/src/data/model/popular_movies_model.dart
> +class PopularMoviesModel {
I notice that you have the same model for Popular, NowPlaying, TopRated and Upcoming, you can just have one model

2023-10-23 14:13 UTC, FranciscoGaraventa commented on lib/src/domain/entities/movie_state.dart
> +  MovieEvent({required this.state, this.data, this.error});
trailing comma

2023-10-23 14:13 UTC, FranciscoGaraventa commented on lib/src/domain/repositories/i_movie_repository.dart
> +  */
Remove unnecessary commented code

2023-10-23 14:14 UTC, FranciscoGaraventa commented on lib/src/presentation/bloc/genres_bloc.dart
> +  //final Mapper mapper = Mapper();
remove commented code

2023-10-23 14:15 UTC, ismaelherrera1 commented on lib/src/data/model/movie_model.dart
> +      //required super.originalTitle,
I don't remember 😅

2023-10-23 14:15 UTC, FranciscoGaraventa commented on lib/src/presentation/bloc/popular_movies_bloc.dart
> +//TODO : DELETE THIS
remove this

2023-10-25 12:32 UTC, Kevin-Guillen commented on lib/src/core/util/enum_states.dart
> +}
missing eof

2023-10-25 12:32 UTC, Kevin-Guillen commented on lib/src/core/util/enum_categories.dart
> +}
missing eof

2023-10-25 12:32 UTC, Kevin-Guillen commented on lib/src/core/util/data_state.dart
> +}
missing eof

2023-10-25 12:33 UTC, Kevin-Guillen commented on lib/src/core/util/movie_related_mocks.dart
> +   */
remove comment

2023-10-25 12:35 UTC, Kevin-Guillen commented on lib/src/data/model/genres_list_model.dart
> +    for (int i = 0; i < json['genres'].length; i++) {
you can use map here

2023-10-25 12:36 UTC, Kevin-Guillen commented on lib/src/data/model/now_playing_movies_model.dart
> +}
missing eof

2023-10-25 12:36 UTC, Kevin-Guillen commented on lib/src/data/model/popular_movies_model.dart
> +}
missing eof

2023-10-25 12:36 UTC, Kevin-Guillen commented on lib/src/domain/entities/genre_state.dart
> +}
missing eof

2023-10-25 12:38 UTC, Kevin-Guillen commented on lib/src/domain/use_cases/implementation/now_playing_use_case.dart
> +}
missing eof

2023-10-25 12:38 UTC, Kevin-Guillen commented on lib/src/domain/use_cases/implementation/top_rated_use_case.dart
> +}
missing eof

2023-10-25 12:38 UTC, Kevin-Guillen commented on lib/src/domain/use_cases/implementation/upcoming_movies_use_case.dart
> +}
missing eof

2023-10-25 12:38 UTC, Kevin-Guillen commented on lib/src/domain/use_cases/usecase_interface/i_use_case.dart
> +}
missing eof

2023-10-25 12:38 UTC, Kevin-Guillen commented on lib/src/presentation/bloc/i_bloc.dart
> +}
missing eof

2023-10-25 12:38 UTC, Kevin-Guillen commented on lib/src/presentation/bloc/now_playing_movies_bloc.dart
> +}
missing eof

2023-10-25 12:38 UTC, Kevin-Guillen commented on lib/src/presentation/bloc/top_rated_movies_bloc.dart
> +}
missing eof

2023-10-25 12:39 UTC, Kevin-Guillen commented on lib/src/presentation/views/about_us_screen.dart
> +              Text(
constant

2023-10-25 12:39 UTC, Kevin-Guillen commented on lib/src/presentation/views/home_page.dart
> +          style: TextStyle(fontFamily: 'Poppins', letterSpacing: 5),
constant

2023-10-25 12:39 UTC, Kevin-Guillen commented on lib/src/presentation/views/movie_details.dart
> +//import '../../domain/entities/genre.dart';
remove comment

2023-10-25 12:40 UTC, Kevin-Guillen commented on lib/src/presentation/views/now_playing_movies_screen.dart
> +        title: const Text('Now Playing',),
constant

2023-10-25 12:40 UTC, Kevin-Guillen commented on lib/src/presentation/views/now_playing_movies_screen.dart
> +                      padding: const EdgeInsets.all(8),
constants

2023-10-25 12:40 UTC, Kevin-Guillen commented on lib/src/presentation/views/popular_movies_screen.dart
> +    //bloc.dispose();
remove comments

2023-10-25 12:42 UTC, Kevin-Guillen requested changes
constants values , eof and remove comments.

2023-10-26 13:30 UTC, FranciscoGaraventa commented on lib/src/core/util/mappers/mapper.dart
> +  Movie movieDataModelToMovie(MovieDataModel movieModel) {
You need this mapper?

2023-10-26 13:33 UTC, MarcosCGlobant requested changes

2023-10-26 13:33 UTC, MarcosCGlobant commented on lib/src/core/util/genre_converter.dart
> +}
format code to remove extra space

2023-10-26 13:33 UTC, MarcosCGlobant commented on lib/src/domain/use_cases/implementation/genres_use_case.dart
> +class GenresUseCase extends UseCase{
as convention, interfaces should start with an I, this one should be IUseCase

2023-10-26 13:33 UTC, MarcosCGlobant commented on lib/src/data/model/movie_model.dart
> +      required super.popularity});
trailing comma missing and format code

2023-10-26 13:33 UTC, MarcosCGlobant commented on lib/src/presentation/views/home_page.dart
> +          style: TextStyle(fontFamily: 'Poppins', letterSpacing: UIConstants.titleLetterSpacing),
trailing comma missing and format code please

2023-10-26 13:33 UTC, MarcosCGlobant commented on lib/src/presentation/views/popular_movies_screen.dart
> +                itemBuilder: (BuildContext context, int index) {
missing trailing commas

2023-10-26 13:33 UTC, MarcosCGlobant commented on lib/src/presentation/views/popular_movies_screen.dart
> +  // TODO: implement wantKeepAlive
what is needed for this implementation?

2023-10-26 13:33 UTC, MarcosCGlobant commented on lib/src/presentation/views/top_rated_movies_screen.dart
> +                  itemBuilder: (BuildContext context, int index) {
missing trailing commas

2023-10-26 13:33 UTC, MarcosCGlobant commented on lib/src/presentation/views/upcoming_movies_screen.dart
> +                  itemBuilder: (BuildContext context, int index) {
missing trailing commas

2023-10-26 13:33 UTC, MarcosCGlobant commented on lib/src/presentation/widgets/my_drawer.dart
> +                    fontSize: UIConstants.titleFontsize, letterSpacing: 5),
trailing comma missing

2023-10-26 13:33 UTC, MarcosCGlobant commented on lib/src/presentation/widgets/nav_bar.dart
> +              duration: const Duration(milliseconds: 200), curve: Curves.ease);
the int should be in a constant

2023-10-26 13:33 UTC, MarcosCGlobant commented on lib/src/presentation/widgets/nav_bar.dart
> +          label: 'ABOUT US',
make hardcode into a constant

2023-10-26 13:33 UTC, MarcosCGlobant commented on lib/src/presentation/widgets/nav_bar.dart
> +          label: 'HOME',
make hardcode into a constant

2023-10-26 13:33 UTC, MarcosCGlobant commented on lib/src/presentation/widgets/nav_bar.dart
> +  NavBar({super.key, required this.selectedItem, required this.controller});
missing trailing comma

2023-10-26 13:33 UTC, MarcosCGlobant commented on test/widget_testing/genre_tile_test.dart
> +    //final text = find.byKey(const Key('genreNameText'));
remove commented code if not needed

2023-10-26 13:33 UTC, MarcosCGlobant commented on test/widget_testing/movie_actions_test.dart
> +}
add EoF line

2023-10-26 13:33 UTC, MarcosCGlobant commented on test/widget_testing/movie_header_test.dart
> +}
add EoF line

2023-10-26 13:33 UTC, MarcosCGlobant commented on test/widget_testing/movie_overview_test.dart
> +//TODO: NO SE COMO SE HACE ESTE HIJO DE PUTA
please blame in english or better yet, don't type it at all

2023-10-26 13:33 UTC, MarcosCGlobant commented on test/widget_testing/movie_overview_test.dart
> +//TODO: NO SE COMO SE HACE ESTE HIJO DE PUTA
if the class cannot be tested, reach for the mentors or explain why it cant and leave it out of the PR

2023-10-26 13:33 UTC, MarcosCGlobant commented on test/widget_testing/movie_tile_test.dart
> +
missing trailing comma

2023-10-26 13:33 UTC, MarcosCGlobant commented on test/widget_testing/nav_bar_test.dart
> +    );
missing trailing comma

2023-10-26 13:33 UTC, ismaelherrera1 commented on test/widget_testing/movie_overview_test.dart
> +//TODO: NO SE COMO SE HACE ESTE HIJO DE PUTA
my bad, forgot to delete it before the pr, sorry for that

2023-10-26 13:34 UTC, MarcosCGlobant commented on lib/src/presentation/views/popular_movies_screen.dart
> +                itemBuilder: (BuildContext context, int index) {
i saw that you have 3 grid views a little similar between them, look if it can be abstracted into a more general widget

2023-10-26 13:39 UTC, ismaelherrera1 commented on lib/src/presentation/views/popular_movies_screen.dart
> +  // TODO: implement wantKeepAlive
when I swap to the about us page, the bloc from the home page is disposed and therefore its content is lost. Kevo suggested it and it worked out for me

2023-10-26 13:42 UTC, FranciscoGaraventa commented on lib/src/presentation/bloc/genres_bloc.dart
> +      }
You can use a ternary here, like
```
_genres.sink.add(
         genres.data != null && genres.state == BaseState.success ? 
         GenresState.success(genreList: genres.data) : 
         GenresState.error(error: genres.error!)
);
```

2023-10-26 13:43 UTC, FranciscoGaraventa commented on lib/src/presentation/bloc/movies_bloc.dart
> +      _movies.sink.add(MovieEvent(state: BaseState.success, data: data.data));
trailing comma

2023-10-26 13:43 UTC, FranciscoGaraventa commented on lib/src/presentation/views/home_page.dart
> +    )),
trailing comma

2023-10-26 13:45 UTC, FranciscoGaraventa commented on lib/src/presentation/views/now_playing_movies_screen.dart
> +          builder: (context, snapshot) {
Add the type of parameters and you missed a trailing comma

2023-10-26 13:45 UTC, FranciscoGaraventa commented on lib/src/presentation/views/now_playing_movies_screen.dart
> +      ),),
format?

2023-10-26 13:45 UTC, FranciscoGaraventa commented on lib/src/presentation/views/now_playing_movies_screen.dart
> +                  itemBuilder: (BuildContext context, int index) {
trailing comma

2023-10-26 13:47 UTC, FranciscoGaraventa commented on lib/src/presentation/views/popular_movies_screen.dart
> +                itemBuilder: (BuildContext context, int index) {
trailing comma

2023-10-26 13:47 UTC, FranciscoGaraventa commented on lib/src/presentation/views/popular_movies_screen.dart
> +        builder: (context, snapshot) {
Add type of parameters and trailing comma

2023-10-26 13:48 UTC, FranciscoGaraventa commented on lib/src/presentation/views/top_rated_movies_screen.dart
> +      ),),
format

2023-10-26 13:50 UTC, FranciscoGaraventa commented on lib/src/presentation/views/top_rated_movies_screen.dart
> +                    return Padding(
Add values to const, trailing commas

2023-10-26 13:51 UTC, FranciscoGaraventa commented on lib/src/presentation/views/upcoming_movies_screen.dart
> +        title: Text(title,),
format

2023-10-26 13:51 UTC, FranciscoGaraventa commented on lib/src/presentation/views/upcoming_movies_screen.dart
> +                      padding: const EdgeInsets.all(8),
Same as above

2023-10-26 13:52 UTC, FranciscoGaraventa commented on lib/src/presentation/widgets/genre_tile.dart
> +      key: const Key('container',),
You can move all the keys to a Keys file, and also made more descriptive key names

2023-10-26 13:54 UTC, FranciscoGaraventa commented on lib/src/presentation/widgets/my_drawer.dart
> +class MyDrawer extends StatelessWidget {
Add values to const, review missed trailing commas

2023-10-26 13:55 UTC, FranciscoGaraventa commented on lib/src/presentation/widgets/my_drawer.dart
> +class MyDrawer extends StatelessWidget {
And you missed to format the file

2023-10-26 13:55 UTC, FranciscoGaraventa commented on lib/src/presentation/widgets/nav_bar.dart
> +              duration: const Duration(milliseconds: 200), curve: Curves.ease);
Values to const and trailing comma

2023-10-31 12:21 UTC, FranciscoGaraventa approved these changes

2023-10-31 12:43 UTC, Kevin-Guillen approved these changes

2023-10-31 13:04 UTC, MarcosCGlobant approved these changes

2023-10-31 13:29 UTC, matiasilveiro-gl approved these changes

2023-10-31 14:06 UTC, merged